-- Check which stock tables exist
SELECT 
    TABLE_NAME,
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = t.TABLE_NAME) AS ColumnCount
FROM INFORMATION_SCHEMA.TABLES t
WHERE TABLE_NAME LIKE '%Stock%'
  AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME

-- Check RetailStock structure
PRINT ''
PRINT '=== RetailStock Table ==='
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'RetailStock'
ORDER BY ORDINAL_POSITION

-- Check Retail_Stock structure
PRINT ''
PRINT '=== Retail_Stock Table ==='
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Retail_Stock'
ORDER BY ORDINAL_POSITION

-- Check Demo_Retail_Stock structure
PRINT ''
PRINT '=== Demo_Retail_Stock Table ==='
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Demo_Retail_Stock'
ORDER BY ORDINAL_POSITION
