-- Check what POS tables actually exist in the database
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE 'POS_%'
ORDER BY TABLE_NAME;

-- Check if POS_ReturnItems exists and its columns
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'POS_ReturnItems'
ORDER BY ORDINAL_POSITION;

-- Check if it might be named differently
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Return%'
ORDER BY TABLE_NAME;
